### ISSUE TITLE
Question about Credit&Charge Invoice Subscription Array

### ISSUE THREAD

**Issue by MiellyEllen** [killbilling/recurly-java-library#286]
Hi Guys, Thanks for your work on the implementing the new webhooks.

I noticed in the XML examples of <new_charge_invoice_notification> and <new_credit_invoice_notification>(https://dev.recurly.com/page/webhooks#charge-invoice-notifications,) contains an array of subscription ids, while <new_invoice_notification> just contains a single <subscription_id> tag.
If we receive either of these new webhooks, and get the PushInvoice off of the notification, What is returned from PushInvoice.getSubscriptionId() ?
Thanks,
Mary Ellen

**Comment by aaron-suarez** [comment]
Well, the super unhelpful (but true) answer to your question is that `PushInvoice.getSubscriptionId()` will return `null` all the time because there is no `<subscription_id>` tag on the invoice level of the XML.

This question actually demonstrates an oversight wherein PushInvoice has no `getSubscriptionIdArray()` method to actually use the subscription IDs that are sent with the webhook.

I'm going to open a PR to add in a method to perform this functionality, then you'll be able to store or use those ids upon receiving these webhooks. Good catch, thanks for letting us know.

**Comment by MiellyEllen** [comment]
Thanks for the quick PR. So, Recurly will be phasing out the legacy invoices so there will be a period of time where we will need to support them as well as the new charge/credit invoices. It's ok that the legacy are marked @deprecated. Just don't take them away too soon :)

**Comment by aaron-suarez** [comment]
We won't take them away until the code that produces them gets removed from Recurly App. They will probably remain in there marked as deprecated for a very long time

**Comment by MiellyEllen** [comment]
Great. Any chance this can get published soon? That way we can code to it early into our sprint so our analyst can do some real testing as soon as possible. We'll give you our feedback

**Comment by aaron-suarez** [comment]
The next release is scheduled for October 30th. Do you need it sooner than that?

**Comment by MiellyEllen** [comment]
Yes, We have a recurly testing environment where we can actually start trying out the credit and charge webhooks  rather than waiting for the actual production drop of November 1st. We would like to shake out any bugs now as well as add extra regression testing for this new process.

**Comment by bhelx** [comment]
@pierre Could we get a release out when you have some spare time?

**Comment by pierre** [comment]
0.20.0 has been released 👍

**Comment by MiellyEllen** [comment]
you guys rock! Thanks so much @pierre . Will let you know our testing results in the next couple weeks

**Comment by bhelx** [comment]
Thanks @pierre !
