### ISSUE TITLE
Webhook Notification missing expires_at date time field in subscription

### ISSUE THREAD

**Issue by cyu521** [killbilling/recurly-java-library#313]
on expired_subscription_notification XML
There is a expires_at field under subscription

<?xml version="1.0" encoding="UTF-8"?>
<scheduled_subscription_pause_notification>
    ...
   <subscription>
   ...
    <expires_at type="datetime">2010-09-24T22:05:03Z</expires_at>
  </subscription>
</scheduled_subscription_pause_notification>
Using
ExpiredSubscriptionNotification, I tried to go to
expiredSubscriptionNotification.subscription.expires_at and that field doesn't exists.

please add that field to the Subscription Object and when parsing it.

Thanks

**Comment by aaron-suarez** [comment]
@cyu521 The expires_at field is already on the Subscription class. `PushSubscription` extends `Subscription` so it should have a method called `getExpiresAt()`.

https://github.com/killbilling/recurly-java-library/blob/ac853e95e913b3e5f86bde4b5eeabb81076a2a1f/src/main/java/com/ning/billing/recurly/model/Subscription.java#L277

Have you tried using this method instead of trying to access that private property directly?

**Comment by cyu521** [comment]
Thanks, I must've missed that!
