### ISSUE TITLE
Is "Recurly-Skip-Authorization" possible?

### ISSUE THREAD

**Issue by jan-ee** [killbilling/recurly-java-library#363]
Hi! We have some accounts that we need to migrate from our old billing system into Recurly. i found that there is a "Recurly-Skip-Authorization" header that can be used to prevent a credit card from being authorized again when getting imported into Recurly. (Something like `.addHeader("Recurly-Skip-Authorization", "true")`).

Is there a way to access this functionality, or a way to add custom headers to an enpoint call, using this library?

Thanks so much for your input!

Jan

**Comment by slisaasquatch** [comment]
Disclaimer: I'm not a developer of this library, but I'm kind of familiar with how this library works because I've been maintaining 2 forks in recent years.

In its current form, it's not possible to add headers, but it shouldn't be crazy to add the feature in. If the developers of this library is interested, I can add it in my fork mentioned in this ticket https://github.com/killbilling/recurly-java-library/issues/355.

**Comment by joannasese** [comment]
Hi @jan-ee. Picking this up. Is this a mission-critical feature/something you still need?

**Comment by jan-ee** [comment]
Hi @joannasese. No, this is not something we really need. After analyzing our code, it was only used during the initial import of billing informatrion into recurly.

Thanks for following up!

**Comment by joannasese** [comment]
Hi @jan-ee. Good to hear! I'll go ahead and close this issue then, but if this feature ends up being essential, let us know.
