### ISSUE TITLE
TLS 1.1 or later

### ISSUE THREAD

**Issue by jtvgithub** [killbilling/recurly-java-library#96]
I am getting following warning in Recurly console. Please help -

**Important Notice: We have detected API connections to this Recurly subdomain using TLS 1.0. For security reasons these connections must be upgraded to TLS 1.1 or later by June 30th, 2016.**

**Comment by bhelx** [comment]
Hey @jtvgithub

Can you tell us what Operating System you are using and which version of Java you are using?

**Comment by jtvgithub** [comment]
After updating Java, this problem is solved.

**Comment by bhelx** [comment]
@jtvgithub Glad it's working for you. Going to close this ticket.

Could you let us know which version you were on and what you updated to? If someone comes searching it would be helpful if they could find some information.

**Comment by bhelx** [comment]
@pierre We are transitioning everyone over to TLS1.1 and TLS1.2 over the summer for PCI compliance reasons (TLS1.0 being deprecated). As far as I can read, Java7 supports these protocols only if you explicitly enable them in the VM and Java8 enables them by default. Do you know if we need to change anything with `AsyncHttpClient` so that it can use the most up to date protocol?

**Comment by bhelx** [comment]
@jtvgithub Did you update from 7 to 8?

**Comment by pierre** [comment]
@bhelx I would guess it's a JVM configuration issue, AHC will simply delegate protocol management to the JVM.

That being said, if you want to enforce the TLS version, this might be possible via [configuration](https://github.com/killbill/killbill-plugin-framework-java/blob/7fac2b75992de3f244e530ce1e8db15a3823cbbd/src/main/java/org/killbill/billing/plugin/util/http/HttpClient.java#L87).

**Comment by bhelx** [comment]
Okay great, I just want to get a plan before we close this issue again. I'm gonna do a couple experiments and some reading and get back.

Will also be updating our TLS 1.0 deprecation document with the plan:

https://dev.recurly.com/v2.0/page/tls-v10-deprecation

**Comment by bhelx** [comment]
@pierre From what I can tell, both 1.7 and 1.8 support TLS 1.1 and 1.2. Version 1.8 will do the negotiation properly on it's own but on version 1.7 we must pass in the protocol to the `getInstance` method on the SSLContext. Would you recommend that I make a PR against your killbill-plugin-framework-java project? What should the configuration look like? Should we just set the protocol to 1.2 automatically if the project is using 1.7 or should there be some other way for the client to configure the protocol?

**Comment by bhelx** [comment]
Or perhaps we can use the `setSSLContext` method on the config builder and allow the client to pass in their own context object?

https://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncHttpClientConfig.Builder.html#setSSLContext%28javax.net.ssl.SSLContext%29

**Comment by pierre** [comment]
> Would you recommend that I make a PR against your killbill-plugin-framework-java project? 

While it would be nice to have that piece of code shared, the Recurly client doesn't rely on killbill-plugin-framework-java (and I'm not sure we want to, since it would pull OSGI). So we would need to copy this code over (including the bits from [SslUtils](https://github.com/killbill/killbill-plugin-framework-java/blob/master/src/main/java/org/killbill/billing/plugin/util/http/SslUtils.java)).

> Should we just set the protocol to 1.2 automatically if the project is using 1.7 or should there be some other way for the client to configure the protocol?

I would make it configurable, with a sane default (e.g. v1.2). It looks like you can configure it directly in the `SSLSocketFactory` (see https://github.com/zuora/rest-java-client/pull/7).

**Comment by jtvgithub** [comment]
I updated to 1.8 ... Sorry for the delay... I was on leave...

**Comment by bhelx** [comment]
@jtvgithub thanks for updating us

**Comment by bhelx** [comment]
@pierre I'll do a follow up PR

**Comment by bhelx** [comment]
We can consider this done for now due to https://github.com/killbilling/recurly-java-library/pull/110

I'm going to update our TLS deprecation docs and adding a README PR here:

https://github.com/killbilling/recurly-java-library/pull/111
